# book settings
title: sim-tools docs
author: Thomas Monks
email: t.m.w.monks@exeter.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  sim-tools documentation
#logo: content/imgs/logo_v1.png

# only build files specified in table of contents file
only_build_toc_files: true

execute:
  execute_notebooks: force #cache output from .ipynb files for faster build
  timeout: -1 #no time restriction on notebook execution
  
repository:
  url: https://github.com/TomMonks/sim-tools
  branch: main
  
html:
  use_repository_button: true
  use_issues_button: true
  
# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  notebook_interface: "jupyterlab"
  thebe: true

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js