name: sim_tools
channels:
  - conda-forge
dependencies:
  - jupyter-book=1.0.3
  - jupyterlab=4.3.5
  - jupyterlab-plotly-extension=1.0.0
  - matplotlib=3.9.1
  - numpy=2.2.2
  - pandas=2.2.3
  - pip=25.0
  - plotly=6.0.0
  - pytest=8.3.4
  - python=3.11
  - scipy=1.15.1
  - pip:
      - -e ../

