name: sim_tools
channels:
  - conda-forge
dependencies:
  - matplotlib=3.8.2
  - numpy=1.26.0
  - pandas=2.1.3
  - pip=23.3.1
  - pytest=7.4.3
  - python=3.11
  - scipy=1.11.3
  - pip:
    - sim-tools
