name: sim_tools_dev
channels:
  - conda-forge
dependencies:
  - jupyterlab=3.4.8
  - jupyterlab-spellchecker=0.7.2
  - matplotlib=3.3.4
  - numpy=1.19.2
  - pandas=1.2.3
  - pip=21.0.1
  - pytest=7.1.3
  - pytest-cov=4.0.0
  - python=3.8.12
  - scipy=1.6.1
  - seaborn=0.10.0
  - pip:
    - sim-tools
