name: sim_tools_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab=3.0.8
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandas=1.0.1
  - pip=20.0.2
  - pytest=5.3.5
  - python=3.8.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - pip:
    - pytest-cov==2.10.0
    - setuptools>=51.1.2
    - twine>=3.3.0
    - wheel
    - sim-tools
